# vim: ft=yaml ts=2 sw=2 et :
image: archlinux
packages:
  - meson
  - xorg-server-xwayland
  - xcb-util-image
  - json-c
  - pango
  - cairo
  - wayland
  - wayland-protocols
  - gdk-pixbuf2
  - libinput
  - libxkbcommon
sources:
  - https://git.sr.ht/~sircmpwn/sway
  - https://git.sr.ht/~sircmpwn/wlroots
tasks:
  - wlroots: |
      cd wlroots
      meson --prefix=/usr build
      ninja -C build
      sudo ninja -C build install
  - setup: |
      cd sway
      meson build
  - build: |
      cd sway
      ninja -C build
