blank_issues_enabled: false
contact_links:
  - name: Questions
    url: "https://kiwiirc.com/nextclient/irc.libera.chat:+6697/#sway"
    about: "Please ask questions on IRC in #sway on irc.libera.chat"
